version: '3.3'
services:
  backend_history_1:
    container_name: backend_history_1
    restart: always
    build: .
    ports:
      - '7002:7002'
    volumes:
      - .:/app/code
  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./APIBackendService/web:/etc/nginx/html
      - ./APIBackendService/static:/etc/nginx/html/static
    ports:
      - "7878:7878"
    depends_on:
      - backend_history_1
