# Generated by Django 3.0.6 on 2022-11-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Waiting for the start'), (2, 'Preparing to start'), (3, 'Game in progress'), (5, 'Completed')], default=1)),
                ('is_automatic', models.IntegerField(default=0)),
                ('timestamp_create', models.DateTimeField(auto_now_add=True)),
                ('timestamp_start', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(verbose_name='Duration in seconds')),
                ('bet', models.IntegerField(verbose_name='Bet')),
                ('questions_category', models.IntegerField(choices=[(1, 'All'), (2, 'Ancient times'), (3, 'New time'), (4, 'Modernity')])),
            ],
            options={
                'ordering': ['timestamp_create'],
            },
        ),
        migrations.CreateModel(
            name='CompletedDuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_create', models.DateTimeField()),
                ('timestamp_end', models.DateTimeField(auto_now_add=True)),
                ('is_automatic', models.IntegerField()),
                ('duration', models.IntegerField(verbose_name='Duration in seconds')),
                ('bet', models.IntegerField(verbose_name='Bet')),
                ('questions_category', models.IntegerField(choices=[(1, 'All'), (2, 'Ancient times'), (3, 'New time'), (4, 'Modernity')])),
            ],
        ),
        migrations.CreateModel(
            name='DuelsConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DuelTrainerBlockRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DuelUserState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('question_index', models.IntegerField(default=0)),
                ('rating_changes', models.FloatField(default=0.0)),
            ],
        ),
    ]
