# Generated by Django 3.0.6 on 2022-11-23 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Games', '0001_initial'),
        ('Content', '0002_auto_20221123_2033'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dueluserstate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dueltrainerblockrelation',
            name='active_duel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Games.ActiveDuel'),
        ),
        migrations.AddField(
            model_name='dueltrainerblockrelation',
            name='trainer_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Content.TrainerBlock'),
        ),
        migrations.AddField(
            model_name='completedduel',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_completed_duel', to='Games.DuelUserState'),
        ),
        migrations.AddField(
            model_name='completedduel',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_completed_duel', to='Games.DuelUserState'),
        ),
        migrations.AddField(
            model_name='activeduel',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_active_duel', to='Games.DuelUserState'),
        ),
        migrations.AddField(
            model_name='activeduel',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_active_duel', to='Games.DuelUserState'),
        ),
        migrations.AddField(
            model_name='activeduel',
            name='trainer_blocks',
            field=models.ManyToManyField(blank=True, related_name='trainer_blocks', through='Games.DuelTrainerBlockRelation', to='Content.TrainerBlock'),
        ),
    ]
