# Generated by Django 3.0.6 on 2022-11-23 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Content', '0002_auto_20221123_2033'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermetric',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranswerforreview',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.TrainerBlock'),
        ),
        migrations.AddField(
            model_name='useranswerforreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerblockprogress',
            name='trainer_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.TrainerBlock'),
        ),
        migrations.AddField(
            model_name='trainerblockprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerblocklog',
            name='trainer_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.TrainerBlock'),
        ),
        migrations.AddField(
            model_name='trainerblocklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productprogress',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='Content.Product'),
        ),
        migrations.AddField(
            model_name='productprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.Product'),
        ),
        migrations.AddField(
            model_name='productlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='initlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answersprogressstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usermetric',
            constraint=models.UniqueConstraint(fields=('user', 'metric'), name='user_metric_unique'),
        ),
        migrations.AddIndex(
            model_name='trainerblockprogress',
            index=models.Index(fields=['user', 'trainer_block'], name='Statistics__user_id_155806_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainerblockprogress',
            constraint=models.UniqueConstraint(fields=('user', 'trainer_block'), name='unique_pair'),
        ),
        migrations.AddIndex(
            model_name='productprogress',
            index=models.Index(fields=['user', 'product'], name='Statistics__user_id_5040ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='productprogress',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_product'),
        ),
    ]
